### ISSUE TITLE
Research Oauth 2 - we make ot or not?

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/robolo#10]

**Comment by olafkrawczyk** [comment]
Możemy zostawić to na koniec projektu. http://adam.wroclaw.pl/2014/10/oauth2-wyjasniony-po-ludzku/
Z tego wynika, że do OAuth2 potrzebny jest trzeci serwer jako provider w związku z tym musielibyśmy wykorzystać istniejącego usługodawcę (np. facebook) https://spring.io/guides/tutorials/spring-boot-oauth2/#_social_login_simple. Nie wygląda to na skomplikowane

**Comment by majcherpiotrek** [comment]
Nie robimy, nie będzie czasu się z tym bawić raczej
