### ISSUE TITLE
TaskItem - service, DTO, controller

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/robolo#15]

**Comment by szachnowicz** [comment]
Czy potrzebna jest classa TaskItemTO ? w kodzie jeszcze jej nie  a nie wiem czy to planowane działanie czy Ci się nie chciało :P

**Comment by majcherpiotrek** [comment]
Nie potrzebna będzie, wywalamy. Entity będziemy używać bo to będzie szło tylko wewnątrz taska
