### ISSUE TITLE
Brak połączenia encji Project z User

### ISSUE THREAD

**Issue by olafkrawczyk** [piotrmajcher94/robolo#27]
Nie da się połączyć projektu z użytkownikiem, potrzebna będzie tablica asocjacyjna czy inne gunwo XD

**Comment by majcherpiotrek** [comment]
Wiem, specjalnie nie ma, bo ogarniam nadal.temat sesji użytkownika i jeszcze nie wiem do końca jak to wtedy będzie zrobione. Poki co można już jakieś inne serwisy klepać bo najwyżej się dopiszę tam potem jakiś jeden warunek where userid=costam . Ale to jak będzie gotowe to zedytujemy tego sqla
